name: Run checks
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm install @biomejs/biome@1.8.3
      - run: npm install rollup@4.20.0
      - run: cat package.json
      - run: npm run check:ci
      - run: npm run type-check
      - run: npm test
