name: Run checks
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: biomejs/setup-biome@v2
        with:
          biome-version: 1.8.3
      - run: npm ci
      - run: cat package.json
      - run: npm run check:ci
      - run: npm run type-check
      - run: npm test
